from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


# class Ui_MainWindow(object):
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         MainWindow.resize(766, 260)
#         MainWindow.setMinimumSize(QtCore.QSize(766, 260))
#         MainWindow.setMaximumSize(QtCore.QSize(766, 260))
#         MainWindow.setStyleSheet(
#             "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0 rgba(244, 247, 255, 255), stop:1 rgba(255, 255, 255, 255))")
#         self.centralwidget = QtWidgets.QWidget(MainWindow)
#         self.centralwidget.setObjectName("centralwidget")
#         self.label_6 = QtWidgets.QLabel(self.centralwidget)
#         self.label_6.setGeometry(QtCore.QRect(420, 70, 96, 16))
#         self.label_6.setScaledContents(False)
#         self.label_6.setWordWrap(False)
#         self.label_6.setObjectName("label_6")
#         self.label_9 = QtWidgets.QLabel(self.centralwidget)
#         self.label_9.setGeometry(QtCore.QRect(420, 90, 60, 16))
#         self.label_9.setObjectName("label_9")
#         self.label_4 = QtWidgets.QLabel(self.centralwidget)
#         self.label_4.setGeometry(QtCore.QRect(420, 50, 96, 16))
#         self.label_4.setScaledContents(False)
#         self.label_4.setWordWrap(False)
#         self.label_4.setObjectName("label_4")
#         self.label_2 = QtWidgets.QLabel(self.centralwidget)
#         self.label_2.setGeometry(QtCore.QRect(420, 30, 60, 16))
#         self.label_2.setObjectName("label_2")
#         self.label_7 = QtWidgets.QLabel(self.centralwidget)
#         self.label_7.setGeometry(QtCore.QRect(380, 120, 149, 16))
#         self.label_7.setScaledContents(False)
#         self.label_7.setWordWrap(False)
#         self.label_7.setObjectName("label_7")
#         self.label_3 = QtWidgets.QLabel(self.centralwidget)
#         self.label_3.setGeometry(QtCore.QRect(460, 30, 80, 16))
#         self.label_3.setObjectName("label_3")
#         self.label_5 = QtWidgets.QLabel(self.centralwidget)
#         self.label_5.setGeometry(QtCore.QRect(520, 50, 110, 16))
#         self.label_5.setObjectName("label_5")
#         self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
#         self.textBrowser.setGeometry(QtCore.QRect(380, 140, 340, 120))
#         self.textBrowser.setObjectName("textBrowser")
#         self.listWidget = QtWidgets.QListWidget(self.centralwidget)
#         self.listWidget.setGeometry(QtCore.QRect(30, 70, 250, 190))
#         self.listWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
#         self.listWidget.setObjectName("listWidget")
#         self.label = QtWidgets.QLabel(self.centralwidget)
#         self.label.setGeometry(QtCore.QRect(120, 50, 60, 16))
#         self.label.setObjectName("label")
#         self.label_8 = QtWidgets.QLabel(self.centralwidget)
#         self.label_8.setGeometry(QtCore.QRect(470, 90, 90, 16))
#         self.label_8.setObjectName("label_8")
#         self.pushButton = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton.setGeometry(QtCore.QRect(20, 290, 131, 32))
#         self.pushButton.setObjectName("pushButton")
#         self.grafikb = QtWidgets.QPushButton(self.centralwidget)
#         self.grafikb.setGeometry(QtCore.QRect(150, 290, 131, 32))
#         self.grafikb.setObjectName("grafikb")
#         MainWindow.setCentralWidget(self.centralwidget)
#         self.label_10 = QtWidgets.QLabel(self.centralwidget)
#         self.label_10.setGeometry(QtCore.QRect(500, 70, 90, 16))
#         self.label_10.setObjectName("label_10")
#         self.updbtn = QtWidgets.QPushButton(self.centralwidget)
#         self.updbtn.setGeometry(QtCore.QRect(210, 40, 71, 32))
#         self.updbtn.setObjectName("pushButton_2")
#
#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)
#
#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
#         self.label_6.setText(_translate("MainWindow", "Что делаем: "))
#         self.label_9.setText(_translate("MainWindow", "Номер: "))
#         self.label_4.setText(_translate("MainWindow", "Время записи: "))
#         self.label_2.setText(_translate("MainWindow", "Имя:"))
#         self.label_7.setText(_translate("MainWindow", "Особенности клиента:"))
#         self.label_3.setText(_translate("MainWindow", ""))
#         self.label_5.setText(_translate("MainWindow", ""))
#         self.textBrowser.setHtml(_translate("MainWindow", ""))
#         __sortingEnabled = self.listWidget.isSortingEnabled()
#         self.listWidget.setSortingEnabled(False)
#         self.listWidget.setSortingEnabled(__sortingEnabled)
#         self.label.setText(_translate("MainWindow", "Сегодня"))
#         self.label_8.setText(_translate("MainWindow", ""))
#         self.pushButton.setText(_translate("MainWindow", "Управление БД"))
#         self.grafikb.setText(_translate("MainWindow", "Записи"))
#         self.updbtn.setText(_translate("MainWindow", "update"))

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(766, 260)
        MainWindow.setMinimumSize(QtCore.QSize(766, 260))
        MainWindow.setMaximumSize(QtCore.QSize(766, 260))
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0 rgba(244, 247, 255, 255), stop:1 rgba(255, 255, 255, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ysluga_txt = QtWidgets.QLabel(self.centralwidget)
        self.ysluga_txt.setGeometry(QtCore.QRect(62, 71, 51, 16))
        self.ysluga_txt.setStyleSheet("background: transparent;")
        self.ysluga_txt.setScaledContents(False)
        self.ysluga_txt.setWordWrap(False)
        self.ysluga_txt.setObjectName("ysluga_txt")
        self.phone_txt = QtWidgets.QLabel(self.centralwidget)
        self.phone_txt.setGeometry(QtCore.QRect(182, 50, 114, 15))
        self.phone_txt.setStyleSheet("background: transparent;")
        self.phone_txt.setObjectName("phone_txt")
        self.zapis_txt = QtWidgets.QLabel(self.centralwidget)
        self.zapis_txt.setGeometry(QtCore.QRect(62, 50, 67, 16))
        self.zapis_txt.setStyleSheet("background: transparent;")
        self.zapis_txt.setScaledContents(False)
        self.zapis_txt.setWordWrap(False)
        self.zapis_txt.setObjectName("zapis_txt")
        self.client_txt = QtWidgets.QLabel(self.centralwidget)
        self.client_txt.setGeometry(QtCore.QRect(58, 29, 49, 16))
        self.client_txt.setStyleSheet("background: transparent;")
        self.client_txt.setObjectName("client_txt")
        self.osobi = QtWidgets.QLabel(self.centralwidget)
        self.osobi.setGeometry(QtCore.QRect(32, 90, 149, 16))
        self.osobi.setStyleSheet("background: transparent;")
        self.osobi.setScaledContents(False)
        self.osobi.setWordWrap(False)
        self.osobi.setObjectName("osobi")
        self.client_txt1 = QtWidgets.QLabel(self.centralwidget)
        self.client_txt1.setGeometry(QtCore.QRect(107, 29, 202, 16))
        self.client_txt1.setStyleSheet("background: transparent;")
        self.client_txt1.setObjectName("client_txt1")
        self.time_txt = QtWidgets.QLabel(self.centralwidget)
        self.time_txt.setGeometry(QtCore.QRect(130, 50, 37, 16))
        self.time_txt.setStyleSheet("background: transparent;")
        self.time_txt.setObjectName("time_txt")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 111, 353, 120))
        self.textBrowser.setStyleSheet("border-radius: 15px; \n"
                                        "border-style: outset;")
        self.textBrowser.setObjectName("textBrowser")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(420, 60, 311, 111))
        self.listWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget.setStyleSheet("border-radius: 15px; \n"
                                        "border-style: outset;")
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setAlternatingRowColors(False)
        self.listWidget.setObjectName("listWidget")
        self.zn_txt = QtWidgets.QLabel(self.centralwidget)
        self.zn_txt.setGeometry(QtCore.QRect(440, 28, 123, 15))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.zn_txt.setFont(font)
        self.zn_txt.setStyleSheet("background: transparent;")
        self.zn_txt.setObjectName("zn_txt")
        self.phone_txt2 = QtWidgets.QLabel(self.centralwidget)
        self.phone_txt2.setGeometry(QtCore.QRect(302, 50, 91, 16))
        self.phone_txt2.setStyleSheet("background: transparent;")
        self.phone_txt2.setObjectName("phone_txt2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(440, 202, 130, 35))
        font = QtGui.QFont()
        font.setFamily("SF Pro")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
                                      "border-radius: 10px; \n"
                                      "border-style: outset;\n"
                                      "background-color: rgb(255, 255, 255);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color: rgb(222, 221, 235);\n"
                                      "color: rgb(113, 75, 244)\n"
                                      "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./img/gg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.yslyga_txt2 = QtWidgets.QLabel(self.centralwidget)
        self.yslyga_txt2.setGeometry(QtCore.QRect(112, 71, 160, 16))
        self.yslyga_txt2.setStyleSheet("background: transparent;")
        self.yslyga_txt2.setObjectName("yslyga_txt2")
        self.updbtn = QtWidgets.QPushButton(self.centralwidget)
        self.updbtn.setGeometry(QtCore.QRect(640, 20, 81, 32))
        self.updbtn.setStyleSheet("QPushButton{\n"
                                  "border-radius: 10px; \n"
                                  "border-style: outset;\n"
                                  "background-color: rgb(255, 255, 255);\n"
                                  "}\n"
                                  "QPushButton:hover{\n"
                                  "background-color: rgb(222, 221, 235);\n"
                                  "color: rgb(113, 75, 244)\n"
                                  "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./img/uod.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updbtn.setIcon(icon1)
        self.updbtn.setIconSize(QtCore.QSize(30, 30))
        self.updbtn.setObjectName("updbtn")
        self.grafikb = QtWidgets.QPushButton(self.centralwidget)
        self.grafikb.setGeometry(QtCore.QRect(574, 202, 130, 35))
        self.grafikb.setStyleSheet("QPushButton{\n"
                                   "border-radius: 10px; \n"
                                   "border-style: outset;\n"
                                   "background-color: rgb(255, 255, 255);\n"
                                   "}\n"
                                   "QPushButton:hover{\n"
                                   "background-color: rgb(222, 221, 235);\n"
                                   "color: rgb(113, 75, 244)\n"
                                   "}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./img/calen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.grafikb.setIcon(icon2)
        self.grafikb.setIconSize(QtCore.QSize(30, 30))
        self.grafikb.setObjectName("grafikb")
        self.iconfig_btn = QtWidgets.QLabel(self.centralwidget)
        self.iconfig_btn.setGeometry(QtCore.QRect(404, 190, 351, 58))
        self.iconfig_btn.setStyleSheet("background: transparent;")
        self.iconfig_btn.setText("")
        self.iconfig_btn.setPixmap(QtGui.QPixmap("./img/cnopki.png"))
        self.iconfig_btn.setScaledContents(True)
        self.iconfig_btn.setObjectName("iconfig_btn")
        self.iconfig_grf = QtWidgets.QLabel(self.centralwidget)
        self.iconfig_grf.setGeometry(QtCore.QRect(400, 8, 361, 181))
        self.iconfig_grf.setText("")
        self.iconfig_grf.setPixmap(QtGui.QPixmap("./img/border1.png"))
        self.iconfig_grf.setScaledContents(True)
        self.iconfig_grf.setWordWrap(False)
        self.iconfig_grf.setObjectName("iconfig_grf")
        self.icon_zp = QtWidgets.QLabel(self.centralwidget)
        self.icon_zp.setGeometry(QtCore.QRect(410, 20, 25, 30))
        self.icon_zp.setText("")
        self.icon_zp.setPixmap(QtGui.QPixmap("./img/menu.png"))
        self.icon_zp.setScaledContents(True)
        self.icon_zp.setObjectName("icon_zp")
        self.iconfig_client = QtWidgets.QLabel(self.centralwidget)
        self.iconfig_client.setGeometry(QtCore.QRect(12, 0, 391, 251))
        self.iconfig_client.setText("")
        self.iconfig_client.setPixmap(QtGui.QPixmap("./img/clien.png"))
        self.iconfig_client.setScaledContents(True)
        self.iconfig_client.setObjectName("iconfig_client")
        self.icon_client = QtWidgets.QLabel(self.centralwidget)
        self.icon_client.setGeometry(QtCore.QRect(30, 20, 25, 30))
        self.icon_client.setStyleSheet("background: transparent;")
        self.icon_client.setText("")
        self.icon_client.setPixmap(QtGui.QPixmap("./img/gg.png"))
        self.icon_client.setScaledContents(True)
        self.icon_client.setObjectName("icon_client")
        self.iconfig_client.raise_()
        self.iconfig_grf.raise_()
        self.iconfig_btn.raise_()
        self.ysluga_txt.raise_()
        self.phone_txt.raise_()
        self.zapis_txt.raise_()
        self.client_txt.raise_()
        self.osobi.raise_()
        self.client_txt1.raise_()
        self.time_txt.raise_()
        self.textBrowser.raise_()
        self.listWidget.raise_()
        self.zn_txt.raise_()
        self.phone_txt2.raise_()
        self.pushButton.raise_()
        self.yslyga_txt2.raise_()
        self.updbtn.raise_()
        self.grafikb.raise_()
        self.icon_zp.raise_()
        self.icon_client.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "C&G"))
        self.ysluga_txt.setText(_translate("MainWindow", "Услуга:"))
        self.phone_txt.setText(_translate("MainWindow", "Номер телефона: "))
        self.zapis_txt.setText(_translate("MainWindow", "Запись на"))
        self.client_txt.setText(_translate("MainWindow", "Клиент "))
        self.osobi.setText(_translate("MainWindow", "Особенности клиента"))
        self.client_txt1.setText(_translate("MainWindow", ""))
        self.time_txt.setText(_translate("MainWindow", "10:00"))
        self.textBrowser.setHtml(_translate("MainWindow", ""))
        self.zn_txt.setText(_translate("MainWindow", "Записи на сегодня"))
        self.phone_txt2.setText(_translate("MainWindow", ""))
        self.pushButton.setText(_translate("MainWindow", "Управление БД"))
        self.yslyga_txt2.setText(_translate("MainWindow", ""))
        self.updbtn.setText(_translate("MainWindow", "update"))
        self.grafikb.setText(_translate("MainWindow", "Записи"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


